/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type ShutdownOptions struct {

	// What kind of mechanism used to perform the shutdown operation
	Mechanism string `json:"Mechanism,omitempty"`

	// What is the type of the shutdown operation
	Type string `json:"Type,omitempty"`

	// If this shutdown is forceful or not
	Force bool `json:"Force,omitempty"`

	// Reason for the shutdown
	Reason string `json:"Reason,omitempty"`
}
